#!/usr/bin/env sh
# for this to work you must configure sudo such that
# it will be able to run the command without password

/opt/homebrew/bin/yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo /opt/homebrew/bin/yabai --load-sa
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"

# .. more yabai startup stuff
/opt/homebrew/bin/yabai -m config external_bar all:35:0
/opt/homebrew/bin/yabai -m config mouse_follows_focus off
/opt/homebrew/bin/yabai -m config focus_follows_mouse off
/opt/homebrew/bin/yabai -m config window_zoom_persist off
/opt/homebrew/bin/yabai -m config window_placement second_child
/opt/homebrew/bin/yabai -m config window_opacity off
/opt/homebrew/bin/yabai -m config split_ratio 0.50
/opt/homebrew/bin/yabai -m config auto_balance off
/opt/homebrew/bin/yabai -m config mouse_modifier fn
/opt/homebrew/bin/yabai -m config mouse_action1 move
/opt/homebrew/bin/yabai -m config mouse_action2 resize
/opt/homebrew/bin/yabai -m config mouse_drop_action swap
/opt/homebrew/bin/yabai -m config menubar_opacity 0.0
# /opt/homebrew/bin/yabai -m config window_opacity_duration 0.2
#/opt/homebrew/bin/yabai -m config active_window_opacity 1.0
#/opt/homebrew/bin/yabai -m config normal_window_opacity 0.95
# /opt/homebrew/bin/yabai -m config window_animation_duration 0.5
# /opt/homebrew/bin/yabai -m config auto_padding on
# /opt/homebrew/bin/yabai -m config window_topmost off
# /opt/homebrew/bin/yabai -m config window_shadow float

/opt/homebrew/bin/yabai -m config top_padding 5
/opt/homebrew/bin/yabai -m config bottom_padding 8
/opt/homebrew/bin/yabai -m config left_padding 8
/opt/homebrew/bin/yabai -m config right_padding 8
/opt/homebrew/bin/yabai -m config window_gap 8

# 多桌面配置
# No.1 #

# No.2 #
/opt/homebrew/bin/yabai -m rule --add app="QQ" space=2 manage=on
/opt/homebrew/bin/yabai -m rule --add app="微信" space=2 manage=on

# No.3 #
/opt/homebrew/bin/yabai -m rule --add app="Alacritty" space=3 manage=on

# No.4 #
/opt/homebrew/bin/yabai -m rule --add app="Chrome" space=4 --opacity=0.7 manage=on
/opt/homebrew/bin/yabai -m rule --add app="Ark" space=4 --opacity=0.7 manage=on
/opt/homebrew/bin/yabai -m rule --add app="Notion" space=4 --opacity=0.7 manage=on

# No.5 #
/opt/homebrew/bin/yabai -m rule --add app="goland" space=5 manage=on

# No.6 #
/opt/homebrew/bin/yabai -m rule --add app="网易云音乐" space=6 manage=on
/opt/homebrew/bin/yabai -m rule --add app="飞书" space=6 manage=on

# No.7 #
/opt/homebrew/bin/yabai -m rule --add app="ChatGPT" space=7 manage=on
/opt/homebrew/bin/yabai -m rule --add app="Postman" space=7 manage=on
/opt/homebrew/bin/yabai -m rule --add app="Sublime Text" space=7 manage=on

# Exclude problematic apps from being managed:
/opt/homebrew/bin/yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|App Store|Steam|Alfred|Activity Monitor)$" manage=off
/opt/homebrew/bin/yabai -m rule --add app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
otherApp='^(IINA|Tencent Lemon|Clash Verge|音乐|MotionPro| discover |PlayCover|访达|Calendar|日历|地图|System Preferences|朋友圈|小程序|Downie 4|Shadowrocket| |照片|Epson iProjection|系统设置|1Password 7|Android Studio|印象笔记|MATLAB|CrossOver|飞连|哔哩哔哩)$'
/opt/homebrew/bin/yabai -m rule --add app="${otherApp}" manage=off

/opt/homebrew/bin/yabai -m config layout bsp
yabai -m rule --add app="Alacritty" title="^dropdown-alacritty$" manage=off
echo "yabai configuration loaded.."
