[general]
live_config_reload = true

[window]
startup_mode = "Maximized"
opacity = 0.7
decorations = "none"

[env]
TERM = "xterm-256color"

[font]
size = 15

[font.bold]
family = "Hack Nerd Font"

[font.italic]
family = "Hack Nerd Font"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[mouse]
hide_when_typing = true

[terminal.shell]
program = "/bin/zsh"
args = ["-l"]

[window.padding]
x = 18
y = 16
